// Assessments reference existing, already-seeded Question codes (defined
// alongside each chapter's lessons) rather than duplicating generator specs —
// a Test is a curated selection/ordering of real practice questions, not a
// separate question bank.

export interface AssessmentDef {
  code: string;
  chapterCode: string;
  style: "TEST_A" | "TEST_B";
  title: string;
  description: string;
  questionCodes: string[];
}

export const ASSESSMENTS: AssessmentDef[] = [
  {
    code: "ch1-testA",
    chapterCode: "ch1",
    style: "TEST_A",
    title: "Test A: Numbers to 1,000",
    description: "Key concepts and fundamental skills: building, comparing, and ordering numbers. 20 questions, easy to moderate.",
    questionCodes: [
      "ch1.placevalue.build.q1",
      "ch1.numberline.q1",
      "ch1.order.q3",
      "ch1.placevalue.decompose.q3",
      "ch1.compare.q3",
      "ch1.placevalue.build.q3",
      "ch1.placevalue.decompose.q1",
      "ch1.compare.q1",
      "ch1.numberline.q3",
      "ch1.order.q1",
      "ch1.patterns.q1",
      "ch1.patterns.q2",
      "ch1.review.q1",
      "ch1.review.q2",
      "ch1.numberline.q2",
      "ch1.placevalue.build.q2",
      "ch1.review.q3",
      "ch1.review.q4",
      "ch1.compare.q5",
      "ch1.order.q5",
    ],
  },
  {
    code: "ch1-testB",
    chapterCode: "ch1",
    style: "TEST_B",
    title: "Test B: Numbers to 1,000 — Think It Through",
    description: "Analytical thinking: harder numbers, mixed representations, spot-the-mistake, and riddles. 20 questions, moderate to hard.",
    questionCodes: [
      "ch1.compare.q2",
      "ch1.placevalue.decompose.q2",
      "ch1.order.q2",
      "ch1.patterns.q3",
      "ch1.compare.q4",
      "ch1.compare.q6",
      "ch1.compare.q7",
      "ch1.placevalue.decompose.q4",
      "ch1.placevalue.decompose.q5",
      "ch1.patterns.q4",
      "ch1.patterns.q5",
      "ch1.order.q4",
      "ch1.numberline.q4",
      "ch1.placevalue.build.q4",
      "ch1.placevalue.build.q5",
      "ch1.review.q5",
      "ch1.review.q6",
      "ch1.review.q7",
      "ch1.review.q8",
      "ch1.compare.q5",
    ],
  },
  {
    code: "ch7-testA",
    chapterCode: "ch7",
    style: "TEST_A",
    title: "Test A: ×2, ×5, ×10 Facts",
    description: "Key concepts and fundamental fact recall for the 2, 5, and 10 tables and their division inverses.",
    questionCodes: [
      "ch7.mult5.facts.q1",
      "ch7.mult2.facts.q1",
      "ch7.mult10.facts.q1",
      "ch7.div2.q2",
      "ch7.div5.q2",
      "ch7.div10.q2",
      "ch7.mixed.practice.q1",
    ],
  },
  {
    code: "ch7-testB",
    chapterCode: "ch7",
    style: "TEST_B",
    title: "Test B: ×2, ×5, ×10 — Think It Through",
    description: "Analytical thinking and word problems applying multiplication and division facts to new situations.",
    questionCodes: [
      "ch7.mult5.facts.q2",
      "ch7.mult2.facts.q2",
      "ch7.mult10.facts.q2",
      "ch7.wordproblems.q1",
      "ch7.wordproblems.q2",
      "ch7.wordproblems.q3",
      "ch7.mult5.facts.q3",
      "ch7.mixed.practice.q2",
    ],
  },
  {
    code: "ch2-testA",
    chapterCode: "ch2",
    style: "TEST_A",
    title: "Test A: Addition & Subtraction — Part 1",
    description: "Key concepts and fundamental skills: number bonds, mental addition and subtraction. 20 questions, easy to moderate.",
    questionCodes: [
      "ch2.numberbond.q1",
      "ch2.add.mental.q1",
      "ch2.sub.mental.q1",
      "ch2.compare.wordproblems.q3",
      "ch2.numberbond.q3",
      "ch2.add.mental.q2",
      "ch2.sub.mental.q2",
      "ch2.compare.wordproblems.q1",
      "ch2.partwhole.wordproblems.q1",
      "ch2.partwhole.wordproblems.q2",
      "ch2.review.q1",
      "ch2.review.q2",
      "ch2.review.q3",
      "ch2.numberbond.q2",
      "ch2.add.mental.q3",
      "ch2.sub.mental.q3",
      "ch2.compare.wordproblems.q2",
      "ch2.add.mental.q4",
      "ch2.sub.mental.q4",
      "ch2.numberbond.q4",
    ],
  },
  {
    code: "ch2-testB",
    chapterCode: "ch2",
    style: "TEST_B",
    title: "Test B: Addition & Subtraction — Think It Through",
    description: "Analytical thinking: missing numbers, spot-the-mistake, and two-step word problems. 20 questions, moderate to hard.",
    questionCodes: [
      "ch2.add.mental.q5",
      "ch2.sub.mental.q5",
      "ch2.compare.wordproblems.q4",
      "ch2.partwhole.wordproblems.q3",
      "ch2.partwhole.wordproblems.q4",
      "ch2.partwhole.wordproblems.q5",
      "ch2.partwhole.wordproblems.q6",
      "ch2.review.q4",
      "ch2.review.q5",
      "ch2.review.q6",
      "ch2.review.q7",
      "ch2.review.q8",
      "ch2.numberbond.q4",
      "ch2.numberbond.q2",
      "ch2.add.mental.q3",
      "ch2.add.mental.q4",
      "ch2.sub.mental.q3",
      "ch2.sub.mental.q4",
      "ch2.compare.wordproblems.q2",
      "ch2.compare.wordproblems.q1",
    ],
  },
  {
    code: "ch3-testA",
    chapterCode: "ch3",
    style: "TEST_A",
    title: "Test A: Addition & Subtraction — Part 2",
    description: "Key concepts and fundamental skills: regrouping in addition and subtraction.",
    questionCodes: ["ch3.add.regroup.q1", "ch3.sub.regroup.q1", "ch3.sub.acrosszero.q1", "ch3.mixed.wordproblems.q1"],
  },
  {
    code: "ch3-testB",
    chapterCode: "ch3",
    style: "TEST_B",
    title: "Test B: Addition & Subtraction — Think It Through",
    description: "Analytical thinking: harder regrouping and mixed word problems.",
    questionCodes: [
      "ch3.add.regroup.q2",
      "ch3.sub.regroup.q2",
      "ch3.sub.acrosszero.q2",
      "ch3.mixed.wordproblems.q2",
      "ch3.mixed.wordproblems.q3",
    ],
  },
  {
    code: "ch4-testA",
    chapterCode: "ch4",
    style: "TEST_A",
    title: "Test A: Length",
    description: "Key concepts and fundamental skills: choosing units and measuring length.",
    questionCodes: [
      "ch4.chooseunit.q1",
      "ch4.estimate.measure.q1",
      "ch4.chooseunit.customary.q1",
      "ch4.estimate.measure.inches.q1",
      "ch4.compare.q1",
    ],
  },
  {
    code: "ch4-testB",
    chapterCode: "ch4",
    style: "TEST_B",
    title: "Test B: Length — Think It Through",
    description: "Analytical thinking: trickier unit choices and closer length comparisons.",
    questionCodes: [
      "ch4.chooseunit.q2",
      "ch4.estimate.measure.q2",
      "ch4.chooseunit.customary.q2",
      "ch4.estimate.measure.inches.q2",
      "ch4.compare.q2",
    ],
  },
  {
    code: "ch5-testA",
    chapterCode: "ch5",
    style: "TEST_A",
    title: "Test A: Weight",
    description: "Key concepts and fundamental skills: choosing units and estimating weight.",
    questionCodes: ["ch5.chooseunit.q1", "ch5.estimate.q1", "ch5.chooseunit.customary.q1", "ch5.estimate.customary.q1"],
  },
  {
    code: "ch5-testB",
    chapterCode: "ch5",
    style: "TEST_B",
    title: "Test B: Weight — Think It Through",
    description: "Analytical thinking: trickier unit choices and weight estimates.",
    questionCodes: ["ch5.chooseunit.q2", "ch5.estimate.q2", "ch5.chooseunit.customary.q2", "ch5.estimate.customary.q2"],
  },
  {
    code: "ch6-testA",
    chapterCode: "ch6",
    style: "TEST_A",
    title: "Test A: Multiplication & Division",
    description: "Key concepts and fundamental skills: equal groups, arrays, sharing, grouping, and fact families.",
    questionCodes: [
      "ch6.mult.equalgroups.q1",
      "ch6.mult.arrays.q1",
      "ch6.div.sharing.q1",
      "ch6.div.grouping.q1",
      "ch6.factfamily.q1",
    ],
  },
  {
    code: "ch6-testB",
    chapterCode: "ch6",
    style: "TEST_B",
    title: "Test B: Multiplication & Division — Think It Through",
    description: "Analytical thinking: larger numbers applying equal-groups and sharing/grouping reasoning.",
    questionCodes: [
      "ch6.mult.equalgroups.q2",
      "ch6.mult.arrays.q2",
      "ch6.div.sharing.q2",
      "ch6.div.grouping.q2",
      "ch6.factfamily.q2",
    ],
  },
];
