// Assessments reference existing, already-seeded Question codes (defined
// alongside each chapter's lessons) rather than duplicating generator specs —
// a Test is a curated selection/ordering of real practice questions, not a
// separate question bank.

export interface AssessmentDef {
  code: string;
  chapterCode: string;
  style: "TEST_A" | "TEST_B";
  title: string;
  description: string;
  questionCodes: string[];
}

export const ASSESSMENTS: AssessmentDef[] = [
  {
    code: "g1ch1-testA",
    chapterCode: "g1ch1",
    style: "TEST_A",
    title: "Test A: Numbers to 10",
    description: "Key skills: counting, zero, and getting started with ordering and comparing. 15 questions, easy to moderate.",
    questionCodes: [
      "g1ch1.count.q1",
      "g1ch1.count.q2",
      "g1ch1.count.q3",
      "g1ch1.zero.count.q1",
      "g1ch1.zero.count.q2",
      "g1ch1.zero.count.q3",
      "g1ch1.zero.countback.q1",
      "g1ch1.order.q1",
      "g1ch1.order.q2",
      "g1ch1.order.missing.q1",
      "g1ch1.order.missing.q2",
      "g1ch1.compare.q1",
      "g1ch1.compare.q2",
      "g1ch1.compare.q3",
      "g1ch1.practice.q1",
    ],
  },
  {
    code: "g1ch1-testB",
    chapterCode: "g1ch1",
    style: "TEST_B",
    title: "Test B: Numbers to 10 — Think It Through",
    description: "Harder numbers, backward counting, greatest-to-least ordering, and pictorial comparisons. 15 questions, moderate to hard.",
    questionCodes: [
      "g1ch1.count.q4",
      "g1ch1.count.q5",
      "g1ch1.zero.count.q4",
      "g1ch1.zero.count.q5",
      "g1ch1.zero.countback.q2",
      "g1ch1.zero.countback.q3",
      "g1ch1.order.q3",
      "g1ch1.order.q4",
      "g1ch1.order.q5",
      "g1ch1.order.missing.q3",
      "g1ch1.order.missing.q4",
      "g1ch1.compare.q4",
      "g1ch1.compare.q5",
      "g1ch1.practice.q3",
      "g1ch1.practice.q6",
    ],
  },
  {
    code: "g1ch2-testA",
    chapterCode: "g1ch2",
    style: "TEST_A",
    title: "Test A: Number Bonds",
    description: "Finding missing parts for wholes 6, 7, 8, 9, and getting started with 10. 15 questions, easy to moderate.",
    questionCodes: [
      "g1ch2.make6.q1",
      "g1ch2.make6.q2",
      "g1ch2.make6.q3",
      "g1ch2.make7.q1",
      "g1ch2.make7.q2",
      "g1ch2.make7.q3",
      "g1ch2.make8.q1",
      "g1ch2.make8.q2",
      "g1ch2.make9.q1",
      "g1ch2.make9.q2",
      "g1ch2.make10a.q1",
      "g1ch2.make10a.q2",
      "g1ch2.make10a.q3",
      "g1ch2.practice.q1",
      "g1ch2.practice.q2",
    ],
  },
  {
    code: "g1ch2-testB",
    chapterCode: "g1ch2",
    style: "TEST_B",
    title: "Test B: Number Bonds — Think It Through",
    description: "Harder splits, the \"how many more\" framing, and fast recall of every way to make 10. 15 questions, moderate to hard.",
    questionCodes: [
      "g1ch2.make6.q4",
      "g1ch2.make6.q5",
      "g1ch2.make7.q4",
      "g1ch2.make7.q5",
      "g1ch2.make8.q3",
      "g1ch2.make8.q4",
      "g1ch2.make8.q5",
      "g1ch2.make9.q3",
      "g1ch2.make9.q4",
      "g1ch2.make9.q5",
      "g1ch2.make10a.q4",
      "g1ch2.make10a.q5",
      "g1ch2.make10b.q1",
      "g1ch2.make10b.q2",
      "g1ch2.make10b.q3",
    ],
  },
  {
    code: "g1ch3-testA",
    chapterCode: "g1ch3",
    style: "TEST_A",
    title: "Test A: Addition",
    description: "Putting together, adding more, addition with 0, counting on, and simple stories. 15 questions, easy to moderate.",
    questionCodes: [
      "g1ch3.together.q1",
      "g1ch3.together.q2",
      "g1ch3.together.q3",
      "g1ch3.addmore.q1",
      "g1ch3.addmore.q2",
      "g1ch3.addzero.q1",
      "g1ch3.addzero.q2",
      "g1ch3.addzero.q3",
      "g1ch3.counton.q1",
      "g1ch3.counton.q2",
      "g1ch3.bonds.q1",
      "g1ch3.stories.q1",
      "g1ch3.stories.q2",
      "g1ch3.facts.q1",
      "g1ch3.practice.q1",
    ],
  },
  {
    code: "g1ch3-testB",
    chapterCode: "g1ch3",
    style: "TEST_B",
    title: "Test B: Addition — Think It Through",
    description: "Missing addends, harder stories, and fast fact recall. 15 questions, moderate to hard.",
    questionCodes: [
      "g1ch3.together.q4",
      "g1ch3.together.q5",
      "g1ch3.addmore.q4",
      "g1ch3.addmore.q5",
      "g1ch3.addzero.q4",
      "g1ch3.addzero.q5",
      "g1ch3.bonds.q2",
      "g1ch3.bonds.q3",
      "g1ch3.bonds.q4",
      "g1ch3.bonds.q5",
      "g1ch3.counton.q4",
      "g1ch3.counton.q5",
      "g1ch3.facts.q4",
      "g1ch3.facts.q5",
      "g1ch3.facts.q6",
    ],
  },
  {
    code: "g1ch4-testA",
    chapterCode: "g1ch4",
    style: "TEST_A",
    title: "Test A: Subtraction",
    description: "Taking away, taking apart, counting back, and subtraction with 0. 15 questions, easy to moderate.",
    questionCodes: [
      "g1ch4.takeaway.q1",
      "g1ch4.takeaway.q2",
      "g1ch4.takeaway.q3",
      "g1ch4.takeapart.q1",
      "g1ch4.takeapart.q2",
      "g1ch4.countback.q1",
      "g1ch4.countback.q2",
      "g1ch4.subzero.q1",
      "g1ch4.subzero.q2",
      "g1ch4.subzero.q3",
      "g1ch4.stories.q1",
      "g1ch4.stories.q2",
      "g1ch4.bonds.q1",
      "g1ch4.addsub.q1",
      "g1ch4.addsub.q2",
    ],
  },
  {
    code: "g1ch4-testB",
    chapterCode: "g1ch4",
    style: "TEST_B",
    title: "Test B: Subtraction — Think It Through",
    description: "Missing numbers, fact families connecting addition and subtraction, and fast recall. 15 questions, moderate to hard.",
    questionCodes: [
      "g1ch4.takeaway.q4",
      "g1ch4.takeaway.q5",
      "g1ch4.takeapart.q4",
      "g1ch4.takeapart.q5",
      "g1ch4.countback.q4",
      "g1ch4.countback.q5",
      "g1ch4.bonds.q2",
      "g1ch4.bonds.q3",
      "g1ch4.bonds.q4",
      "g1ch4.bonds.q5",
      "g1ch4.addsub.q3",
      "g1ch4.addsub.q4",
      "g1ch4.addsub.q5",
      "g1ch4.addsub.q6",
      "g1ch4.facts.q1",
    ],
  },
  {
    code: "g1ch5-testA",
    chapterCode: "g1ch5",
    style: "TEST_A",
    title: "Test A: Numbers to 20",
    description: "Composing teen numbers, ordering, comparing, and adding/subtracting within the same ten. 15 questions, easy to moderate.",
    questionCodes: [
      "g1ch5.teen.q1",
      "g1ch5.teen.q2",
      "g1ch5.teen.q3",
      "g1ch5.tensones.q1",
      "g1ch5.tensones.q2",
      "g1ch5.order.q1",
      "g1ch5.order.q3",
      "g1ch5.order.q5",
      "g1ch5.compare.q1",
      "g1ch5.compare.q2",
      "g1ch5.add.q1",
      "g1ch5.add.q2",
      "g1ch5.sub.q1",
      "g1ch5.sub.q2",
      "g1ch5.practice.q1",
    ],
  },
  {
    code: "g1ch5-testB",
    chapterCode: "g1ch5",
    style: "TEST_B",
    title: "Test B: Numbers to 20 — Think It Through",
    description: "Missing numbers, harder comparisons, and fast recall adding/subtracting within 20. 15 questions, moderate to hard.",
    questionCodes: [
      "g1ch5.teen.q4",
      "g1ch5.teen.q5",
      "g1ch5.tensones.q3",
      "g1ch5.tensones.q4",
      "g1ch5.tensones.q5",
      "g1ch5.order.q6",
      "g1ch5.order.q7",
      "g1ch5.compare.q4",
      "g1ch5.compare.q5",
      "g1ch5.add.q4",
      "g1ch5.add.q5",
      "g1ch5.sub.q4",
      "g1ch5.sub.q5",
      "g1ch5.practice.q7",
      "g1ch5.practice.q8",
    ],
  },
  {
    code: "g1ch6-testA",
    chapterCode: "g1ch6",
    style: "TEST_A",
    title: "Test A: Addition to 20",
    description: "Making a ten with 8 or 9 in either position, and getting started on the general case. 12 questions, easy to moderate.",
    questionCodes: [
      "g1ch6.maketen1.q1",
      "g1ch6.maketen1.q2",
      "g1ch6.maketen1.q3",
      "g1ch6.maketen2.q1",
      "g1ch6.maketen2.q2",
      "g1ch6.maketen2.q3",
      "g1ch6.maketen3.q1",
      "g1ch6.maketen3.q2",
      "g1ch6.facts.q1",
      "g1ch6.facts.q2",
      "g1ch6.practice.q1",
      "g1ch6.practice.q2",
    ],
  },
  {
    code: "g1ch6-testB",
    chapterCode: "g1ch6",
    style: "TEST_B",
    title: "Test B: Addition to 20 — Think It Through",
    description: "The general make-a-ten case, missing addends, and fast fact recall. 12 questions, moderate to hard.",
    questionCodes: [
      "g1ch6.maketen1.q4",
      "g1ch6.maketen1.q5",
      "g1ch6.maketen2.q4",
      "g1ch6.maketen2.q5",
      "g1ch6.maketen3.q4",
      "g1ch6.maketen3.q5",
      "g1ch6.facts.q4",
      "g1ch6.facts.q5",
      "g1ch6.facts.q6",
      "g1ch6.practice.q5",
      "g1ch6.practice.q6",
      "g1ch6.practice.q7",
    ],
  },
  {
    code: "g1ch7-testA",
    chapterCode: "g1ch7",
    style: "TEST_A",
    title: "Test A: Subtraction Within 20",
    description: "Subtracting from 10 with 8/9 and 6/7, and getting started subtracting the ones first. 15 questions, easy to moderate.",
    questionCodes: [
      "g1ch7.subten1.q1",
      "g1ch7.subten1.q2",
      "g1ch7.subten1.q3",
      "g1ch7.subten2.q1",
      "g1ch7.subten2.q2",
      "g1ch7.subten2.q3",
      "g1ch7.subones.q1",
      "g1ch7.subones.q2",
      "g1ch7.wordproblems.q1",
      "g1ch7.wordproblems.q2",
      "g1ch7.facts.q1",
      "g1ch7.facts.q2",
      "g1ch7.practice.q1",
      "g1ch7.practice.q2",
    ],
  },
  {
    code: "g1ch7-testB",
    chapterCode: "g1ch7",
    style: "TEST_B",
    title: "Test B: Subtraction Within 20 — Think It Through",
    description: "The general crossing-the-ten case, harder word problems, and fast fact recall. 15 questions, moderate to hard.",
    questionCodes: [
      "g1ch7.subten1.q4",
      "g1ch7.subten1.q5",
      "g1ch7.subten2.q4",
      "g1ch7.subten2.q5",
      "g1ch7.subones.q3",
      "g1ch7.subones.q4",
      "g1ch7.subones.q5",
      "g1ch7.wordproblems.q4",
      "g1ch7.wordproblems.q5",
      "g1ch7.facts.q4",
      "g1ch7.facts.q5",
      "g1ch7.facts.q6",
      "g1ch7.practice.q5",
      "g1ch7.practice.q6",
    ],
  },
  {
    code: "ch1-testA",
    chapterCode: "ch1",
    style: "TEST_A",
    title: "Test A: Numbers to 1,000",
    description: "Key concepts and fundamental skills: building, comparing, and ordering numbers. 20 questions, easy to moderate.",
    questionCodes: [
      "ch1.placevalue.build.q1",
      "ch1.numberline.q1",
      "ch1.order.q3",
      "ch1.placevalue.decompose.q3",
      "ch1.compare.q3",
      "ch1.placevalue.build.q3",
      "ch1.placevalue.decompose.q1",
      "ch1.compare.q1",
      "ch1.numberline.q3",
      "ch1.order.q1",
      "ch1.patterns.q1",
      "ch1.patterns.q2",
      "ch1.review.q1",
      "ch1.review.q2",
      "ch1.numberline.q2",
      "ch1.placevalue.build.q2",
      "ch1.review.q3",
      "ch1.review.q4",
      "ch1.compare.q5",
      "ch1.order.q5",
    ],
  },
  {
    code: "ch1-testB",
    chapterCode: "ch1",
    style: "TEST_B",
    title: "Test B: Numbers to 1,000 — Think It Through",
    description: "Analytical thinking: harder numbers, mixed representations, spot-the-mistake, and riddles. 20 questions, moderate to hard.",
    questionCodes: [
      "ch1.compare.q2",
      "ch1.placevalue.decompose.q2",
      "ch1.order.q2",
      "ch1.patterns.q3",
      "ch1.compare.q4",
      "ch1.compare.q6",
      "ch1.compare.q7",
      "ch1.placevalue.decompose.q4",
      "ch1.placevalue.decompose.q5",
      "ch1.patterns.q4",
      "ch1.patterns.q5",
      "ch1.order.q4",
      "ch1.numberline.q4",
      "ch1.placevalue.build.q4",
      "ch1.placevalue.build.q5",
      "ch1.review.q5",
      "ch1.review.q6",
      "ch1.review.q7",
      "ch1.review.q8",
      "ch1.compare.q5",
    ],
  },
  {
    code: "ch7-testA",
    chapterCode: "ch7",
    style: "TEST_A",
    title: "Test A: ×2, ×5, ×10 Facts",
    description: "Key concepts and fundamental fact recall for the 2, 5, and 10 tables and their division inverses. 20 questions, easy to moderate.",
    questionCodes: [
      "ch7.mult5.table.q1",
      "ch7.mult5.facts.q1",
      "ch7.mult5.practice.q1",
      "ch7.mult2.table.q1",
      "ch7.mult2.facts.q1",
      "ch7.mult2.practice.q1",
      "ch7.mult10.table.q1",
      "ch7.mult10.facts.q1",
      "ch7.div2.q1",
      "ch7.div5.q1",
      "ch7.div10.q1",
      "ch7.mixed.practice.q1",
      "ch7.wordproblems.q1",
      "ch7.review.q1",
      "ch7.mult5.facts.q2",
      "ch7.mult2.facts.q2",
      "ch7.mult10.facts.q2",
      "ch7.wordproblems.q2",
      "ch7.wordproblems.q3",
      "ch7.review.q2",
    ],
  },
  {
    code: "ch7-testB",
    chapterCode: "ch7",
    style: "TEST_B",
    title: "Test B: ×2, ×5, ×10 — Think It Through",
    description: "Analytical thinking: spot-the-mistake, commutative-property claims, relating neighboring facts, and choosing the right operation. 20 questions, moderate to hard.",
    questionCodes: [
      "ch7.mult5.table.q4",
      "ch7.mult5.facts.q4",
      "ch7.mult5.facts.q5",
      "ch7.mult5.practice.q3",
      "ch7.mult5.practice.q4",
      "ch7.mult2.table.q4",
      "ch7.mult2.facts.q4",
      "ch7.mult2.facts.q5",
      "ch7.mult2.practice.q3",
      "ch7.mult2.practice.q4",
      "ch7.mult10.table.q4",
      "ch7.mult10.facts.q3",
      "ch7.mult10.facts.q4",
      "ch7.div2.q4",
      "ch7.div5.q4",
      "ch7.div10.q4",
      "ch7.mixed.practice.q4",
      "ch7.wordproblems.q5",
      "ch7.review.q5",
      "ch7.review.q6",
    ],
  },
  {
    code: "ch2-testA",
    chapterCode: "ch2",
    style: "TEST_A",
    title: "Test A: Addition & Subtraction — Part 1",
    description: "Key concepts and fundamental skills: number bonds, mental addition and subtraction. 20 questions, easy to moderate.",
    questionCodes: [
      "ch2.numberbond.q1",
      "ch2.add.mental.q1",
      "ch2.sub.mental.q1",
      "ch2.compare.wordproblems.q3",
      "ch2.numberbond.q3",
      "ch2.add.mental.q2",
      "ch2.sub.mental.q2",
      "ch2.compare.wordproblems.q1",
      "ch2.partwhole.wordproblems.q1",
      "ch2.partwhole.wordproblems.q2",
      "ch2.review.q1",
      "ch2.review.q2",
      "ch2.review.q3",
      "ch2.numberbond.q2",
      "ch2.add.mental.q3",
      "ch2.sub.mental.q3",
      "ch2.compare.wordproblems.q2",
      "ch2.add.mental.q4",
      "ch2.sub.mental.q4",
      "ch2.numberbond.q4",
    ],
  },
  {
    code: "ch2-testB",
    chapterCode: "ch2",
    style: "TEST_B",
    title: "Test B: Addition & Subtraction — Think It Through",
    description: "Analytical thinking: missing numbers, spot-the-mistake, and two-step word problems. 20 questions, moderate to hard.",
    questionCodes: [
      "ch2.add.mental.q5",
      "ch2.sub.mental.q5",
      "ch2.compare.wordproblems.q4",
      "ch2.partwhole.wordproblems.q3",
      "ch2.partwhole.wordproblems.q4",
      "ch2.partwhole.wordproblems.q5",
      "ch2.partwhole.wordproblems.q6",
      "ch2.review.q4",
      "ch2.review.q5",
      "ch2.review.q6",
      "ch2.review.q7",
      "ch2.review.q8",
      "ch2.numberbond.q4",
      "ch2.numberbond.q2",
      "ch2.add.mental.q3",
      "ch2.add.mental.q4",
      "ch2.sub.mental.q3",
      "ch2.sub.mental.q4",
      "ch2.compare.wordproblems.q2",
      "ch2.compare.wordproblems.q1",
    ],
  },
  {
    code: "ch3-testA",
    chapterCode: "ch3",
    style: "TEST_A",
    title: "Test A: Addition & Subtraction — Part 2",
    description: "Key concepts and fundamental skills: regrouping in addition and subtraction. 20 questions, easy to moderate.",
    questionCodes: [
      "ch3.add.regroup.q1",
      "ch3.sub.regroup.q1",
      "ch3.add.regroup.q3",
      "ch3.sub.regroup.q3",
      "ch3.sub.acrosszero.q3",
      "ch3.mixed.wordproblems.q1",
      "ch3.mixed.wordproblems.q2",
      "ch3.mixed.wordproblems.q3",
      "ch3.review.q1",
      "ch3.review.q2",
      "ch3.review.q3",
      "ch3.add.regroup.q2",
      "ch3.sub.regroup.q2",
      "ch3.sub.acrosszero.q1",
      "ch3.sub.acrosszero.q2",
      "ch3.sub.acrosszero.q4",
      "ch3.mixed.wordproblems.q4",
      "ch3.add.regroup.q5",
      "ch3.sub.regroup.q5",
      "ch3.review.q6",
    ],
  },
  {
    code: "ch3-testB",
    chapterCode: "ch3",
    style: "TEST_B",
    title: "Test B: Addition & Subtraction — Think It Through",
    description: "Analytical thinking: spot-the-mistake, missing numbers, two-step stories, and greatest/least pairs. 20 questions, moderate to hard.",
    questionCodes: [
      "ch3.add.regroup.q4",
      "ch3.sub.regroup.q4",
      "ch3.mixed.wordproblems.q5",
      "ch3.mixed.wordproblems.q6",
      "ch3.mixed.wordproblems.q7",
      "ch3.mixed.wordproblems.q8",
      "ch3.review.q4",
      "ch3.review.q5",
      "ch3.review.q7",
      "ch3.review.q8",
      "ch3.sub.acrosszero.q2",
      "ch3.sub.acrosszero.q4",
      "ch3.mixed.wordproblems.q4",
      "ch3.add.regroup.q2",
      "ch3.sub.regroup.q2",
      "ch3.add.regroup.q5",
      "ch3.sub.regroup.q5",
      "ch3.review.q2",
      "ch3.review.q6",
      "ch3.sub.acrosszero.q1",
    ],
  },
  {
    code: "ch4-testA",
    chapterCode: "ch4",
    style: "TEST_A",
    title: "Test A: Length",
    description: "Key concepts and fundamental skills: choosing units and measuring length. 20 questions, easy to moderate.",
    questionCodes: [
      "ch4.chooseunit.q1",
      "ch4.estimate.measure.q1",
      "ch4.chooseunit.customary.q1",
      "ch4.estimate.measure.inches.q1",
      "ch4.compare.q1",
      "ch4.chooseunit.q2",
      "ch4.estimate.measure.q2",
      "ch4.chooseunit.customary.q2",
      "ch4.estimate.measure.inches.q2",
      "ch4.compare.q2",
      "ch4.review.q1",
      "ch4.review.q2",
      "ch4.review.q3",
      "ch4.review.q4",
      "ch4.chooseunit.q3",
      "ch4.estimate.measure.q3",
      "ch4.chooseunit.customary.q3",
      "ch4.estimate.measure.inches.q3",
      "ch4.chooseunit.q4",
      "ch4.chooseunit.customary.q4",
    ],
  },
  {
    code: "ch4-testB",
    chapterCode: "ch4",
    style: "TEST_B",
    title: "Test B: Length — Think It Through",
    description: "Analytical thinking: reasonable estimates, ruler-reading mistakes, and three-way comparisons. 20 questions, moderate to hard.",
    questionCodes: [
      "ch4.estimate.measure.q4",
      "ch4.estimate.measure.inches.q4",
      "ch4.compare.q3",
      "ch4.compare.q4",
      "ch4.compare.q5",
      "ch4.compare.q6",
      "ch4.review.q5",
      "ch4.review.q6",
      "ch4.review.q7",
      "ch4.review.q8",
      "ch4.chooseunit.q4",
      "ch4.chooseunit.customary.q4",
      "ch4.estimate.measure.q3",
      "ch4.estimate.measure.inches.q3",
      "ch4.chooseunit.q3",
      "ch4.chooseunit.customary.q3",
      "ch4.compare.q1",
      "ch4.compare.q2",
      "ch4.review.q3",
      "ch4.review.q4",
    ],
  },
  {
    code: "ch5-testA",
    chapterCode: "ch5",
    style: "TEST_A",
    title: "Test A: Weight",
    description: "Key concepts and fundamental skills: choosing units and estimating weight. 20 questions, easy to moderate.",
    questionCodes: [
      "ch5.chooseunit.q1",
      "ch5.estimate.q1",
      "ch5.chooseunit.customary.q1",
      "ch5.estimate.customary.q1",
      "ch5.chooseunit.q2",
      "ch5.estimate.q2",
      "ch5.chooseunit.customary.q2",
      "ch5.estimate.customary.q2",
      "ch5.review.q1",
      "ch5.review.q2",
      "ch5.review.q3",
      "ch5.review.q4",
      "ch5.chooseunit.q3",
      "ch5.estimate.q3",
      "ch5.chooseunit.customary.q3",
      "ch5.estimate.customary.q3",
      "ch5.chooseunit.q4",
      "ch5.chooseunit.customary.q4",
      "ch5.estimate.q4",
      "ch5.estimate.customary.q4",
    ],
  },
  {
    code: "ch5-testB",
    chapterCode: "ch5",
    style: "TEST_B",
    title: "Test B: Weight — Think It Through",
    description: "Analytical thinking: balance-scale sums, missing weights, and weight comparisons. 20 questions, moderate to hard.",
    questionCodes: [
      "ch5.estimate.q5",
      "ch5.estimate.customary.q5",
      "ch5.review.q5",
      "ch5.review.q6",
      "ch5.review.q7",
      "ch5.review.q8",
      "ch5.estimate.q4",
      "ch5.estimate.customary.q4",
      "ch5.chooseunit.q4",
      "ch5.chooseunit.customary.q4",
      "ch5.estimate.q3",
      "ch5.estimate.customary.q3",
      "ch5.chooseunit.q3",
      "ch5.chooseunit.customary.q3",
      "ch5.review.q1",
      "ch5.review.q2",
      "ch5.review.q3",
      "ch5.review.q4",
      "ch5.chooseunit.q2",
      "ch5.estimate.q2",
    ],
  },
  {
    code: "ch6-testA",
    chapterCode: "ch6",
    style: "TEST_A",
    title: "Test A: Multiplication & Division",
    description: "Key concepts and fundamental skills: equal groups, arrays, sharing, grouping, and fact families. 20 questions, easy to moderate.",
    questionCodes: [
      "ch6.mult.equalgroups.q1",
      "ch6.mult.arrays.q1",
      "ch6.div.sharing.q1",
      "ch6.div.grouping.q1",
      "ch6.factfamily.q1",
      "ch6.mult.equalgroups.q2",
      "ch6.mult.arrays.q2",
      "ch6.div.sharing.q2",
      "ch6.div.grouping.q2",
      "ch6.factfamily.q2",
      "ch6.review.q1",
      "ch6.review.q2",
      "ch6.review.q3",
      "ch6.mult.equalgroups.q3",
      "ch6.mult.arrays.q3",
      "ch6.div.sharing.q3",
      "ch6.div.grouping.q3",
      "ch6.factfamily.q3",
      "ch6.mult.equalgroups.q5",
      "ch6.div.sharing.q5",
    ],
  },
  {
    code: "ch6-testB",
    chapterCode: "ch6",
    style: "TEST_B",
    title: "Test B: Multiplication & Division — Think It Through",
    description: "Analytical thinking: find-the-mistake, commutative-property claims, and choosing the right operation. 20 questions, moderate to hard.",
    questionCodes: [
      "ch6.mult.equalgroups.q4",
      "ch6.mult.arrays.q4",
      "ch6.mult.arrays.q5",
      "ch6.div.sharing.q4",
      "ch6.div.grouping.q4",
      "ch6.div.grouping.q5",
      "ch6.factfamily.q4",
      "ch6.factfamily.q5",
      "ch6.review.q4",
      "ch6.review.q5",
      "ch6.review.q6",
      "ch6.review.q7",
      "ch6.review.q8",
      "ch6.mult.equalgroups.q5",
      "ch6.div.sharing.q5",
      "ch6.mult.equalgroups.q3",
      "ch6.mult.arrays.q3",
      "ch6.div.sharing.q3",
      "ch6.div.grouping.q3",
      "ch6.factfamily.q3",
    ],
  },
];
