import type { WeekDef } from "../weekTypes";

const MORNING: WeekDef["days"][number]["activities"][number] = {
  domain: "MORNING",
  type: "MORNING_ROUTINE",
  title: "Good Morning!",
  instructions: "Start the day by checking in.",
  content: { prompt: "How are you feeling this morning?" },
};

export const week1: WeekDef = {
  number: 1,
  theme: "All About Me",
  days: [
    {
      dayNumber: 1,
      title: "Me!",
      activities: [
        MORNING,
        {
          domain: "LITERACY",
          type: "QUESTION",
          title: "Find Your Name",
          instructions: "Tap the word that spells your name.",
          content: { generatorId: "prek.name.recognize", params: {}, difficulty: 1 },
        },
        {
          domain: "MATH",
          type: "QUESTION",
          title: "Counting to 5",
          instructions: "Count the dots and tap the matching number.",
          content: { generatorId: "prek.numeral.match", params: { min: 1, max: 5 }, difficulty: 1 },
        },
        {
          domain: "SCIENCE",
          type: "QUESTION",
          title: "My Body",
          instructions: "Figure out which body part does the job.",
          content: { generatorId: "prek.science.bodyParts", params: {}, difficulty: 1 },
        },
        {
          domain: "WRITING",
          type: "JOURNAL",
          title: "Draw Yourself",
          instructions: "Draw a picture of you!",
          content: { prompt: "Draw a picture of yourself today." },
        },
        {
          domain: "READ_ALOUD",
          type: "READ_ALOUD",
          title: "Story Time",
          instructions: "A parent reads this book together, then asks the questions below.",
          content: {
            bookTitle: "The Colors of Us",
            bookAuthor: "Karen Katz",
            beforeQuestion: "Look at the cover — what do you think this book is about?",
            duringQuestions: [
              "What colors do you see on this page?",
              "How is this character like you? How is she different?",
            ],
            afterQuestion: "What was your favorite part of the story?",
          },
        },
        {
          domain: "MOVEMENT",
          type: "MOVEMENT_BREAK",
          title: "Freeze Dance",
          instructions: "Dance around! When the timer ends, freeze like a statue.",
          content: { description: "Put on your favorite song and dance until the timer goes off — then freeze!", timerSeconds: 60 },
          optional: true,
        },
      ],
    },
    {
      dayNumber: 2,
      title: "My Favorites",
      activities: [
        MORNING,
        {
          domain: "LITERACY",
          type: "QUESTION",
          title: "Find Your Name Again",
          instructions: "Tap the word that spells your name.",
          content: { generatorId: "prek.name.recognize", params: {}, difficulty: 1 },
        },
        {
          domain: "MATH",
          type: "QUESTION",
          title: "More or Fewer",
          instructions: "Tap the group with more dots, or fewer — read carefully!",
          content: { generatorId: "prek.compare.quantities", params: { min: 1, max: 5 }, difficulty: 1 },
        },
        {
          domain: "WRITING",
          type: "TRACE",
          title: "Pencil Warm-Up",
          instructions: "Trace the lines with your finger.",
          content: { target: "lines" },
        },
        {
          domain: "CREATIVE",
          type: "JOURNAL",
          title: "Draw Your Favorite Toy",
          instructions: "Draw the toy you love to play with most.",
          content: { prompt: "Draw your favorite toy." },
        },
        {
          domain: "GAME",
          type: "QUESTION",
          title: "Counting Game",
          instructions: "Count the dots and tap the matching number.",
          content: { generatorId: "prek.numeral.match", params: { min: 1, max: 5 }, difficulty: 1 },
        },
        {
          domain: "EXTENSION",
          type: "PARENT_ACTIVITY",
          title: "Favorites Hunt",
          instructions: "Find 5 things you love in your room and tell a grown-up why.",
          content: { description: "Walk around your room together. For each favorite thing your child points to, ask \"why do you love it?\" and talk about their answer." },
          optional: true,
        },
      ],
    },
    {
      dayNumber: 3,
      title: "My Body",
      activities: [
        MORNING,
        {
          domain: "LITERACY",
          type: "QUESTION",
          title: "Letters and Words",
          instructions: "Is it one letter, or a whole word?",
          content: { generatorId: "prek.literacy.letterOrWord", params: {}, difficulty: 1 },
        },
        {
          domain: "MATH",
          type: "QUESTION",
          title: "Counting to 5",
          instructions: "Count the dots and tap the matching number.",
          content: { generatorId: "prek.numeral.match", params: { min: 1, max: 5 }, difficulty: 1 },
        },
        {
          domain: "SCIENCE",
          type: "EXPERIMENT",
          title: "Can You Feel Your Heartbeat?",
          instructions: "Let's find out what happens to your heartbeat when you move!",
          content: {
            ask: "Can you feel your heart beating right now, while you're sitting still?",
            predictChoices: ["Yes, I can feel it", "No, I don't feel it", "Not sure"],
            testInstructions: "Run in place or jump up and down until the timer ends, then sit down and put your hand on your chest.",
            testTimerSeconds: 20,
            observeChoices: ["My heart is beating fast!", "My heart feels the same", "I'm not sure"],
            recordSummary: "Moving your body makes your heart beat faster to send energy everywhere it's needed. That's your heart working hard for you!",
          },
        },
        {
          domain: "SOCIAL_STUDIES",
          type: "SEL_SCENARIO",
          title: "Sharing a Toy",
          instructions: "What should you do?",
          content: {
            scenario: "Your friend is holding the toy you really want to play with. What should you do?",
            choices: [
              { text: "Grab it from them", feedback: "Grabbing can hurt feelings — let's try something kinder.", isBest: false },
              { text: "Ask for a turn", feedback: "Great choice! Asking nicely is the best way to get a turn.", isBest: true },
              { text: "Yell and cry", feedback: "Yelling doesn't help us get a turn. Try using your words instead.", isBest: false },
            ],
          },
        },
        {
          domain: "MOVEMENT",
          type: "MOVEMENT_BREAK",
          title: "Simon Says",
          instructions: "Play Simon Says using body parts — \"Simon says touch your nose!\"",
          content: { description: "Take turns being \"Simon\" and giving body-part commands: touch your toes, wiggle your ears, clap your hands.", timerSeconds: 120 },
          optional: true,
        },
      ],
    },
    {
      dayNumber: 4,
      title: "My Family & Feelings",
      activities: [
        MORNING,
        {
          domain: "LITERACY",
          type: "QUESTION",
          title: "Find Your Name",
          instructions: "Tap the word that spells your name.",
          content: { generatorId: "prek.name.recognize", params: {}, difficulty: 1 },
        },
        {
          domain: "MATH",
          type: "QUESTION",
          title: "More or Fewer",
          instructions: "Tap the group with more dots, or fewer — read carefully!",
          content: { generatorId: "prek.compare.quantities", params: { min: 1, max: 5 }, difficulty: 1 },
        },
        {
          domain: "SOCIAL_STUDIES",
          type: "SEL_SCENARIO",
          title: "Feeling Upset",
          instructions: "What should you do?",
          content: {
            scenario: "You're feeling really frustrated because a puzzle piece won't fit. What should you do?",
            choices: [
              { text: "Throw the puzzle", feedback: "Throwing things can hurt someone or break something. Let's find a calmer way.", isBest: false },
              { text: "Take 3 deep breaths and try again", feedback: "Wonderful! Taking deep breaths helps your body feel calm again.", isBest: true },
              { text: "Give up and walk away forever", feedback: "It's okay to take a short break, but coming back to try again helps you learn!", isBest: false },
            ],
          },
        },
        {
          domain: "WRITING",
          type: "TRACE",
          title: "Trace Your Name",
          instructions: "Trace over your name with your finger.",
          content: { target: "name" },
        },
        {
          domain: "EXTENSION",
          type: "PARENT_ACTIVITY",
          title: "Family Portrait",
          instructions: "Draw your family together and name each person.",
          content: { description: "On a big piece of paper, draw everyone in your family together. Ask your child to name each person and what they love about them." },
          optional: true,
        },
      ],
    },
    {
      dayNumber: 5,
      title: "All About Me Review",
      activities: [
        MORNING,
        {
          domain: "LITERACY",
          type: "QUESTION",
          title: "Find Your Name",
          instructions: "Tap the word that spells your name.",
          content: { generatorId: "prek.name.recognize", params: {}, difficulty: 1 },
        },
        {
          domain: "MATH",
          type: "QUESTION",
          title: "Counting to 5",
          instructions: "Count the dots and tap the matching number.",
          content: { generatorId: "prek.numeral.match", params: { min: 1, max: 5 }, difficulty: 1 },
        },
        {
          domain: "SCIENCE",
          type: "QUESTION",
          title: "My Body",
          instructions: "Figure out which body part does the job.",
          content: { generatorId: "prek.science.bodyParts", params: {}, difficulty: 1 },
        },
        {
          domain: "WRITING",
          type: "JOURNAL",
          title: "What I Love About Me",
          instructions: "Draw your favorite thing about yourself!",
          content: { prompt: "What is your favorite thing about yourself? Draw it!" },
        },
        {
          domain: "READ_ALOUD",
          type: "READ_ALOUD",
          title: "Story Time",
          instructions: "A parent reads this book together, then asks the questions below.",
          content: {
            bookTitle: "I Like Myself!",
            bookAuthor: "Karen Beaumont",
            beforeQuestion: "What do you think it means to like yourself?",
            duringQuestions: ["What is this character proud of?", "What silly things does she say about herself?"],
            afterQuestion: "What is one thing you like about yourself?",
          },
        },
        {
          domain: "EXTENSION",
          type: "QUESTION",
          title: "Counting Challenge",
          instructions: "Ready for a bigger challenge? Count all the way to 10!",
          content: { generatorId: "prek.numeral.match", params: { min: 6, max: 10 }, difficulty: 1 },
          optional: true,
        },
      ],
    },
  ],
};
